# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='ricepes',
            new_name='recipes',
        ),
    ]
