# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171209_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='genre',
            field=models.CharField(blank=True, choices=[('C', 'Çorbalar'), ('Y', 'Ana Yemek'), ('S', 'Ara Sıcak'), ('M', 'Salata/Meze'), ('T', 'Tatlı')], max_length=80),
        ),
    ]
