# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_food_genre1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cuisine',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
