# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171224_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
