# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171224_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='genre',
            field=models.CharField(blank=True, choices=[('Ç', 'Çorbalar'), ('Y', 'Yemek'), ('A', 'Atıştırmalık'), ('S', 'Salata'), ('T', 'Tatlı')], max_length=80),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Cuisine'),
            preserve_default=False,
        ),
    ]
