# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171224_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='genre',
            field=models.CharField(blank=True, choices=[(b'A', b'Atistirmalik'), (b'T', b'Tatli'), (b'C', b'Corbalar'), (b'S', b'Salata'), (b'Y', b'Yemek')], max_length=80),
        ),
    ]
