# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171227_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Food')),
            ],
        ),
    ]
