# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20171227_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
